name: Build and deploy Python project to Azure Function App - construction

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: 'construction-function'
  DOCKER_REGISTRY: 'mainregistry.azurecr.io' # Replace with your Azure Container Registry URL
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . -t ${{ env.DOCKER_IMAGE_NAME }}:$GITHUB_SHA
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:$GITHUB_SHA ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:$GITHUB_SHA

      - name: Push Docker image to Azure Container Registry
        run: |
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:$GITHUB_SHA

      - name: Upload image tag as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: |
            .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Deploy Docker image to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'construction' # Replace with your Azure Function App name
          slot-name: 'Production'
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:$GITHUB_SHA
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
